const Data = [
	{
		id: "1",
		image: require("./asset/profile1.png"),
		name: "Achmad Hilmy",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "2",
	},
	{
		id: "2",
		image: require("./asset/profile2.png"),
		name: "Badrun",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "4",
	},
	{
		id: "3",
		image: require("./asset/profile3.png"),
		name: "Cacing",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "1",
	},
	{
		id: "4",
		image: require("./asset/profile1.png"),
		name: "Dumbo",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "2",
	},
	{
		id: "5",
		image: require("./asset/profile2.png"),
		name: "Ealah",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "4",
	},
	{
		id: "6",
		image: require("./asset/profile3.png"),
		name: "Fira",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "1",
	},
	{
		id: "7",
		image: require("./asset/profile1.png"),
		name: "G banget",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "2",
	},
	{
		id: "8",
		image: require("./asset/profile2.png"),
		name: "Haduh",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "4",
	},
	{
		id: "9",
		image: require("./asset/profile3.png"),
		name: "Ilang",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "1",
	},
	{
		id: "10",
		image: require("./asset/profile1.png"),
		name: "Jordi",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "2",
	},
	{
		id: "11",
		image: require("./asset/profile1.png"),
		name: "kulbet",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "2",
	},
	{
		id: "12",
		image: require("./asset/profile2.png"),
		name: "Lumi",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "4",
	},
	{
		id: "13",
		image: require("./asset/profile3.png"),
		name: "Mamang",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "1",
	},
	{
		id: "14",
		image: require("./asset/profile1.png"),
		name: "Nang",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "2",
	},
	{
		id: "15",
		image: require("./asset/profile2.png"),
		name: "Orang",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "4",
	},
	{
		id: "16",
		image: require("./asset/profile3.png"),
		name: "Profile",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "1",
	},
	{
		id: "17",
		image: require("./asset/profile1.png"),
		name: "Qiqi",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "2",
	},
	{
		id: "18",
		image: require("./asset/profile2.png"),
		name: "Rest",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "4",
	},
	{
		id: "19",
		image: require("./asset/profile3.png"),
		name: "Stfu",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "1",
	},
];

export { Data };
